#!/bin/bash
initsystem="$(ps -p 1 -o comm=)"
boot="$([ -d /sys/firmware/efi ] && echo "UEFI" || echo "BIOS")"
export disk=""
export bootdisk=""
export rootdisk=""
export swapdisk=""
export homedisk=""
export filesystem=""
export HOMEIS=""
export SWAP=""
export usrchooseinit=""
export likernel=""
export localetime=""
export osprober=""
export userneed=""
export hostname=""
export networkin=""
export dhcpclient=""
export bluetooth=""
export locale=""
