#!/usr/bin/bash

locale=$(grep -Ev '^\s*(#|$)' /etc/locale.gen | head -n 1 | awk '{print $1}')
boot="$([ -d /sys/firmware/efi ] && echo "UEFI" || echo "BIOS")"
export disk=""
export bootdisk=""
export SWAP=""
export swapdisk=""
export filesystem=""
export rootdisk=""
export homedisk=""
export HOMEIS=""
export usrchooseinit=""
export likernel=""
export texteditor=""
export osprober=""
export userneed=""
export rootpass=""
export username=""
export userpass=""
export dhcpclient=""
export networkin=""
export bluetooth=""
export wireless=""
export hostname=""
export locale=""
export localetime=""
